### ISSUE TITLE
border issues in snake game

### ISSUE THREAD

**Issue by BonfaceKilz** [jnduli/python_curses_games#4]
When you hit the top, right, or bottom border, you get:
```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    wrapper(menu)
  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/bonface/SideProjects/python_curses_games/menu.py", line 17, in menu
    display(stdscreen, items)
  File "/home/bonface/SideProjects/python_curses_games/menu.py", line 38, in display
    key_game_launcher(key, items, selected, stdscreen)
  File "/home/bonface/SideProjects/python_curses_games/menu.py", line 57, in key_game_launcher
    items[key](stdscreen)
  File "/home/bonface/SideProjects/python_curses_games/games/snake.py", line 118, in snake_game
    snake.loop()
  File "/home/bonface/SideProjects/python_curses_games/games/snake.py", line 113, in loop
    self.snake[0][1], curses.ACS_CKBOARD)
_curses.error: addch() returned ERR
```
When you hit the `left` button, you are taken to the menu, regardless of whether the game has ended or not. The screen isn't also cleared.

IMO, it should present you with an option to either restart the game or quit.

**Comment by jnduli** [comment]
Nice catch. I'd like the game the logic for this to work as follows:

- If the snake object hits any border, the head just appears from the opposite border of the screen
- If you press an illegal direction, the game doesn't crash but just assumes no key was pressed.

I'll work on logic for the above.
